(let ((counter (lambda (inc)
		 (let ((n 0))
		   (lambda ()
		     (let ((old n))
		       (set! n (fx+ n inc))
		       old))))))
  (let ((c1 (counter 1))
	(c3 (counter 3)))
    (c1)
    (c1)
    (c1)
    (c3)
    (fx+ (c1) (c3))))
